version: '3.4'

services:
  catalog-api:
    # image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: src/
      dockerfile: CatalogService/Catalog.API/Dockerfile
    depends_on:
      catalog-api-db:
        condition: service_healthy
      
  catalog-api-db: 
    image: postgres
  
  seq:
    image: datalust/seq



