services:
  catalog-api:
    # image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: src/
      dockerfile: CatalogService/Catalog.API/Dockerfile
    depends_on:
      catalog-api-db:
        condition: service_healthy
      
  catalog-api-db: 
    image: postgres
  
  seq:
    image: datalust/seq
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    depends_on:
      keycloak-db:
        condition: service_healthy

  keycloak-db: 
    image: postgres
  



