services:
  catalog-api:
    build:
      args: 
        - ARG BUILD_CONFIGURATION=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__CatalogDatabase=${CATALOG_API_DB:-Server=catalog-api-db;Port=5432;Database=catalog-api-database;User Id=catalog-api-app;Password=catalog-api-pass}
      - Serilog__WriteTo__1__Args__serverUrl=${CATALOG_API_SEQ:-http://seq}
    ports:
      - "5100:8080"
      - "5101:8081"
    volumes:
      - ${USER_SECRETS_PATH}:/home/app/.microsoft/usersecrets:ro
      - ${HTTPS_CERT_PATH}:/home/app/.aspnet/https:ro

  catalog-api-db: 
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=catalog-api-app
      - POSTGRES_PASSWORD=catalog-api-pass
      - POSTGRES_DB=catalog-api-database
    volumes:
      - catalog-api-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  seq: 
    restart: always
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    volumes:
      - catalog-api-logs:/data
  
  keycloak:
    command: ["start-dev"]
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL_HOST=keycloak-db
      - KC_DB_USERNAME=keycloak-db-app
      - KC_DB_PASSWORD=keycloak-db-pass
      
    ports:
      - 8080:8080

  keycloak-db: 
    image: postgres
    environment:
      - POSTGRES_USER=keycloak-db-app
      - POSTGRES_PASSWORD=keycloak-db-pass
      - POSTGRES_DB=keycloak
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  catalog-api-db-data:
  keycloak-db-data:
  catalog-api-logs:
