services:
  catalog-api:
    # image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: src/
      dockerfile: CatalogService/Catalog.API/Dockerfile
    depends_on:
      catalog-api-db:
        condition: service_healthy
      
  catalog-api-db: 
    image: postgres
  
  seq:
    image: datalust/seq
  
  keycloak:
    image: quay.io/keycloak/keycloak:26.3.3
    command: ["start-dev"]
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    ports:
      - 8080:8080



