#pragma warning disable 8981
// <auto-generated />
using Catalog.Common.Enums;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
namespace Catalog.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20241105201414_rename-saleseventvehicle-table")]
    partial class renamesaleseventvehicletable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "vehicle_category", new[] { "none", "car", "motorcycle", "bicycle", "van", "truck" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Catalog.Persistence.Entities.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("LocationRegion")
                        .HasColumnType("text")
                        .HasColumnName("location_region");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<string>("ZipCode")
                        .HasColumnType("text")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Catalog.Persistence.Entities.SaleEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<DateTime>("DateEventEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_event_end");

                    b.Property<DateTime>("DateEventStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_event_start");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_sale_events");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_sale_events_client_id");

                    b.ToTable("sale_events", (string)null);
                });

            modelBuilder.Entity("Catalog.Persistence.Entities.SaleEventVehicle", b =>
                {
                    b.Property<int>("SaleEventId")
                        .HasColumnType("integer")
                        .HasColumnName("sale_event_id");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(4, 2)")
                        .HasColumnName("discount");

                    b.HasKey("SaleEventId", "VehicleId")
                        .HasName("pk_sale_event_vehicles");

                    b.HasIndex("VehicleId")
                        .HasDatabaseName("ix_sale_event_vehicles_vehicle_id");

                    b.ToTable("sale_event_vehicles", (string)null);
                });

            modelBuilder.Entity("Catalog.Persistence.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<VehicleCategory>("Category")
                        .HasColumnType("vehicle_category")
                        .HasColumnName("category");

                    b.Property<int>("ClientId")
                        .HasColumnType("integer")
                        .HasColumnName("client_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now() at time zone 'utc'");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Properties")
                        .HasColumnType("jsonb")
                        .HasColumnName("properties");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_vehicles");

                    b.HasIndex("ClientId")
                        .HasDatabaseName("ix_vehicles_client_id");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("Catalog.Persistence.Entities.SaleEvent", b =>
                {
                    b.HasOne("Catalog.Persistence.Entities.Client", "Client")
                        .WithMany("SaleEvents")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_events_clients_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Catalog.Persistence.Entities.SaleEventVehicle", b =>
                {
                    b.HasOne("Catalog.Persistence.Entities.SaleEvent", "SaleEvent")
                        .WithMany("SaleEventVehicle")
                        .HasForeignKey("SaleEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_event_vehicles_sale_events_sale_event_id");

                    b.HasOne("Catalog.Persistence.Entities.Vehicle", "Vehicle")
                        .WithMany("SaleEventVehicle")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sale_event_vehicles_vehicles_vehicle_id");

                    b.Navigation("SaleEvent");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Catalog.Persistence.Entities.Vehicle", b =>
                {
                    b.HasOne("Catalog.Persistence.Entities.Client", "Client")
                        .WithMany("Vehicles")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_clients_client_id");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Catalog.Persistence.Entities.Client", b =>
                {
                    b.Navigation("SaleEvents");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Catalog.Persistence.Entities.SaleEvent", b =>
                {
                    b.Navigation("SaleEventVehicle");
                });

            modelBuilder.Entity("Catalog.Persistence.Entities.Vehicle", b =>
                {
                    b.Navigation("SaleEventVehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
