#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/sdk:8.0
EXPOSE 8080
EXPOSE 8081
ENV ASPNETCORE_HTTP_PORTS=8080
ENV ASPNETCORE_HTTPS_PORTS=8081
ENV ASPNETCORE_ENVIRONMENT=Development
ENV BUILD_CONFIGURATION=Debug

WORKDIR /src

COPY ["CatalogService/Catalog.API/Catalog.API.csproj", "CatalogService/Catalog.API/"]
COPY ["CatalogService/Catalog.Business/Catalog.Business.csproj", "CatalogService/Catalog.Business/"]
COPY ["CatalogService/Catalog.Persistence/Catalog.Persistence.csproj", "CatalogService/Catalog.Persistence/"]
RUN dotnet restore "/src/CatalogService/Catalog.API/Catalog.API.csproj"

COPY ./CatalogService ./CatalogService

WORKDIR "/src/CatalogService/Catalog.API"
RUN dotnet build "./Catalog.API.csproj" -c $BUILD_CONFIGURATION

ENTRYPOINT dotnet run --no-build --no-launch-profile -c $BUILD_CONFIGURATION