using Catalog.API.Middleware;
using Catalog.API.Utils;
using Catalog.Business.Extensions;
using Catalog.Persistence.Extensions;
using FluentValidation;
using Microsoft.AspNetCore.Mvc.ApplicationModels;
using Scalar.AspNetCore;
using Serilog;
using System.Reflection;

Log.Logger = new LoggerConfiguration()
    .MinimumLevel.Override("Microsoft", Serilog.Events.LogEventLevel.Information)
    .WriteTo.Console()
    .CreateBootstrapLogger();

try
{
    var builder = WebApplication.CreateBuilder(args);

    // Add services to the container.
    builder.Services.AddSerilog((services, lc) => lc
        .ReadFrom.Configuration(builder.Configuration)
        .ReadFrom.Services(services)
        .Enrich.FromLogContext()
    );

    builder.Services.AddProblemDetails(opt =>
    {
        opt.CustomizeProblemDetails = ctx =>
        {
            ctx.ProblemDetails.Extensions.Add("instance", string.Join(' ', ctx.HttpContext.Request.Method, ctx.HttpContext.Request.Path));
            // Add or replace approach is intentional. Response automatically generated by framework (at least the BadRequest one) automatically 
            // sets this field to Activity.Current.Id which is not the same as TraceId. As a result logs related to the same request will have different traceId
            ctx.ProblemDetails.Extensions["traceId"] = ctx.HttpContext.TraceIdentifier; 
        };
    });

    builder.Services.AddExceptionHandler<GlobalExceptionHandler>();

    builder.Services.AddBusinessLayer();
    builder.Services.AddPersistence(builder.Configuration);

    builder.Services.AddValidatorsFromAssemblyContaining<Program>();

    // TODO: We also need to validate mapings but for that IMapper object is required, hence it's a bit akward to do this in here.
    // Ideally, one should add an unit test that will call the method to validate mappings
    builder.Services.AddAutoMapper(typeof(Program));

    builder.Services.AddControllers(options =>
    {
        options.Conventions.Add(new RouteTokenTransformerConvention(new KebabNamingParameterTransformer()));
    });

    // Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
    builder.Services.AddEndpointsApiExplorer();
    builder.Services.AddSwaggerGen();

    var app = builder.Build();

    app.UseExceptionHandler();

    // Configure the HTTP request pipeline.
    if (app.Environment.IsDevelopment())
    {

        app.UseSwagger(opt =>
        {
            opt.RouteTemplate = "/openapi/{documentName}.json";
        });
        app.MapScalarApiReference(opt =>
        {
            opt.Title = Assembly.GetExecutingAssembly()?.GetName()?.Name ?? "Mock title";
            opt.DarkMode = true;
            opt.EnabledTargets = [ScalarTarget.CSharp, ScalarTarget.Http, ScalarTarget.Shell, ScalarTarget.JavaScript, ScalarTarget.Python];
            opt.Theme = ScalarTheme.Moon;
        });
    }

    app.UseSerilogRequestLogging();

    app.UseAuthorization();

    app.MapControllers();

    app.Run();

    return 0;
}
catch (Exception ex)
{
    Log.Fatal(ex, "An unhandled exception occurred during bootstrapping");
    return 1;
}
finally
{
    Log.CloseAndFlush();
}